export const WORKFLOW_TEMPLATES = [
  {
    id: "store_intelligence",
    name: "Store Intelligence",
    description: "فحص رابط المتجر ثم استخراج المنتجات والأصول وتحليل العلامة.",
    triggerScreen: "store_setup",
    triggerAction: "فحص المتجر",
    inputSources: ["store_url", "workspace_id", "language_hint"],
    outputsTo: ["store_profile", "product_catalog", "asset_library", "data_sources"],
    steps: [
      {
        id: "crawl_store_pages",
        name: "زحف صفحات المتجر",
        inputFrom: ["store_url"],
        processorType: "tool_call",
        processor: "store_crawler",
        outputKey: "store_raw_snapshot",
        outputType: "raw_store_snapshot",
        destination: "workflow_runs",
        visibility: "admin_only",
        reviewRequired: false,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
      },
      {
        id: "extract_products",
        name: "استخراج المنتجات",
        inputFrom: ["store_raw_snapshot"],
        processorType: "model_call",
        processor: "product_extraction",
        outputKey: "product_candidates",
        outputType: "product_candidates",
        destination: "product_catalog",
        visibility: "reviewer_only",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "campaign_generation",
      },
      {
        id: "detect_assets",
        name: "رصد الأصول والصور",
        inputFrom: ["store_raw_snapshot"],
        processorType: "tool_call",
        processor: "asset_detector",
        outputKey: "asset_candidates",
        outputType: "asset_candidates",
        destination: "asset_library",
        visibility: "reviewer_only",
        reviewRequired: true,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
      },
      {
        id: "analyze_store_brand",
        name: "تحليل هوية المتجر",
        inputFrom: ["store_raw_snapshot", "product_candidates"],
        processorType: "model_call",
        processor: "store_reading",
        outputKey: "brand_insights",
        outputType: "brand_insights",
        destination: "store_setup",
        visibility: "customer_visible",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "campaign_generation",
      },
    ],
  },
  {
    id: "campaign_generation",
    name: "Campaign Generation",
    description: "تحويل Brief الحملة إلى استراتيجية ومخرجات أولية.",
    triggerScreen: "campaign_intake",
    triggerAction: "توليد الحملة",
    inputSources: ["campaign_brief", "store_context", "product_context", "asset_context", "governance_context"],
    outputsTo: ["campaign_detail", "content_studio", "review"],
    steps: [
      {
        id: "validate_campaign_brief",
        name: "فحص اكتمال الـ Brief",
        inputFrom: ["campaign_brief", "product_context"],
        processorType: "policy_check",
        processor: "brief_validation",
        outputKey: "brief_validation_report",
        outputType: "risk_report",
        destination: "review",
        visibility: "reviewer_only",
        reviewRequired: false,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
      },
      {
        id: "build_campaign_strategy",
        name: "بناء استراتيجية الحملة",
        inputFrom: ["campaign_brief", "brand_insights", "product_candidates"],
        processorType: "model_call",
        processor: "campaign_strategy",
        outputKey: "campaign_strategy",
        outputType: "campaign_strategy",
        destination: "campaign_detail",
        visibility: "customer_visible",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "content_generation",
      },
      {
        id: "generate_content_plan",
        name: "تجهيز خطة المخرجات",
        inputFrom: ["campaign_strategy", "selected_channels"],
        processorType: "model_call",
        processor: "ad_copy_generation",
        outputKey: "content_plan",
        outputType: "content_draft",
        destination: "content_studio",
        visibility: "customer_visible",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "risk_review",
      },
    ],
  },
  {
    id: "product_analysis",
    name: "تحليل المنتجات",
    description: "مسار واجهي فقط يوضح عقد تحليل المنتج دون تنفيذ أدوات أو نماذج.",
    trigger: {
      type: "manual",
      startCondition: "required_data_complete",
      eventSource: "product_catalog",
      description: "تشغيل يدوي، عند إضافة منتج، عند تحديث منتج، أو عند وصول بيانات أداء جديدة.",
    },
    triggerScreen: "product_catalog",
    triggerAction: "تحليل المنتج",
    inputSources: ["product_context", "asset_context", "analytics_metrics"],
    outputsTo: ["product_catalog", "campaign_detail", "content_studio"],
    steps: [
      {
        id: "collect_product_context",
        name: "تجميع بيانات المنتج",
        inputRefs: [
          { domain: "product_catalog", field: "product_name" },
          { domain: "product_catalog", field: "category" },
          { domain: "product_catalog", field: "price" },
          { domain: "product_catalog", field: "product_description" },
          { domain: "product_catalog", field: "product_media" },
          { domain: "asset_library", field: "linked_assets" },
          { domain: "data_sources", field: "performance_metrics" },
        ],
        processorType: "tool_call",
        processor: "product_context_loader",
        outputKey: "product_analysis_context",
        outputType: "product_analysis_summary",
        destination: "workflow_runs",
        visibility: "reviewer_only",
        reviewRequired: false,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
        outputName: "سياق تحليل المنتج",
        outputFormat: "json",
        outputDestination: "تشغيلات النظام",
        outputVisibility: "reviewer_only",
        outputReviewRequired: false,
        outputReusable: true,
      },
      {
        id: "evaluate_product_readiness",
        name: "مطالبة تحليل المنتج",
        inputRefs: [
          { domain: "product_catalog", field: "product_name" },
          { domain: "product_catalog", field: "category" },
          { domain: "product_catalog", field: "price" },
          { domain: "product_catalog", field: "product_description" },
          { domain: "asset_library", field: "linked_assets" },
        ],
        processorType: "model_call",
        processor: "product_analysis",
        outputKey: "product_readiness_report",
        outputType: "product_analysis_summary",
        destination: "product_catalog",
        visibility: "customer_visible",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "campaign_generation",
        outputName: "ملخص تحليل المنتج",
        outputFormat: "preview_card",
        outputDestination: "كتالوج المنتجات",
        outputVisibility: "customer_visible",
        outputReviewRequired: true,
        outputReusable: true,
        nextRouteEnabled: true,
        nextRoute: "campaign_generation",
        nextStep: "build_campaign_strategy",
        transitionCondition: "after_review",
        nextRouteInputs: ["product_analysis_summary", "product_context"],
      },
      {
        id: "publish_product_analysis_summary",
        name: "إرسال ملخص التحليل",
        inputRefs: [
          { domain: "manual", field: "previous_outputs" },
        ],
        processorType: "data_transform",
        processor: "product_analysis",
        outputKey: "campaign_recommendations",
        outputType: "product_campaign_suggestions",
        destination: "content_studio",
        visibility: "customer_visible",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "content_generation",
        outputName: "اقتراحات الحملات",
        outputFormat: "list",
        outputDestination: "استوديو المحتوى",
        outputVisibility: "customer_visible",
        outputReviewRequired: true,
        outputReusable: true,
      },
    ],
  },
  {
    id: "content_generation",
    name: "Content Regeneration",
    description: "إعادة توليد محتوى محدد من Content Studio.",
    triggerScreen: "content_studio",
    triggerAction: "إعادة توليد",
    inputSources: ["content_id", "campaign_brief", "selected_assets", "output_type"],
    outputsTo: ["content_studio", "review"],
    steps: [
      {
        id: "load_content_context",
        name: "تحميل سياق المحتوى",
        inputFrom: ["content_id", "campaign_brief"],
        processorType: "tool_call",
        processor: "content_context_loader",
        outputKey: "content_context",
        outputType: "raw_store_snapshot",
        destination: "workflow_runs",
        visibility: "admin_only",
        reviewRequired: false,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
      },
      {
        id: "rewrite_content",
        name: "إعادة صياغة المحتوى",
        inputFrom: ["content_context", "brand_insights"],
        processorType: "model_call",
        processor: "content_rewrite",
        outputKey: "content_draft",
        outputType: "content_draft",
        destination: "content_studio",
        visibility: "customer_visible",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "risk_review",
      },
    ],
  },
  {
    id: "video_generation",
    name: "Video Generation",
    description: "سيناريو ظاهر للعميل، مطالبة داخلية، مراجعة مخاطر، ثم توليد فيديو.",
    triggerScreen: "content_studio",
    triggerAction: "توليد فيديو",
    inputSources: ["campaign_brief", "product_context", "approved_assets", "channel_specs", "governance_context"],
    outputsTo: ["content_studio", "asset_library", "review", "workflow_runs"],
    steps: [
      {
        id: "write_customer_video_brief",
        name: "كتابة شرح الفيديو للعميل",
        inputFrom: ["campaign_brief", "product_context"],
        processorType: "model_call",
        processor: "video_script_generation",
        outputKey: "customer_video_brief",
        outputType: "customer_visible_brief",
        destination: "content_studio",
        visibility: "customer_visible",
        reviewRequired: true,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
      },
      {
        id: "write_internal_video_prompt",
        name: "كتابة مطالبة الفيديو الداخلية",
        inputFrom: ["customer_video_brief", "approved_assets", "brand_rules"],
        processorType: "model_call",
        processor: "video_script_generation",
        outputKey: "internal_video_prompt",
        outputType: "internal_prompt",
        destination: "workflow_runs",
        visibility: "internal_only",
        reviewRequired: true,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
      },
      {
        id: "review_video_prompt",
        name: "مراجعة المخاطر والادعاءات",
        inputFrom: ["internal_video_prompt", "customer_video_brief", "approved_assets"],
        processorType: "model_call",
        processor: "risk_review",
        outputKey: "risk_clearance",
        outputType: "risk_report",
        destination: "review",
        visibility: "reviewer_only",
        reviewRequired: true,
        feedsNextWorkflow: false,
        nextWorkflowType: "",
      },
      {
        id: "generate_video_asset",
        name: "إرسال إلى نموذج الفيديو",
        inputFrom: ["risk_clearance", "internal_video_prompt", "approved_assets"],
        processorType: "model_call",
        processor: "video_generation",
        outputKey: "generated_video_asset",
        outputType: "generated_asset",
        destination: "asset_library",
        visibility: "reviewer_only",
        reviewRequired: true,
        feedsNextWorkflow: true,
        nextWorkflowType: "publishing",
      },
    ],
  },
];

export const PROCESSOR_TYPES = [
  ["tool_call", "استدعاء أداة"],
  ["model_call", "استدعاء نموذج"],
  ["human_review", "مراجعة بشرية"],
  ["asset_check", "فحص أصول"],
  ["cost_check", "فحص تكلفة"],
  ["policy_check", "فحص سياسة"],
  ["data_transform", "تحويل بيانات"],
];

export const PROCESSORS = [
  ["store_crawler", "Store Crawler"],
  ["social_analyzer", "Social Analyzer"],
  ["product_extraction", "Product Extraction"],
  ["product_analysis", "تحليل المنتج"],
  ["product_context_loader", "تحميل سياق المنتج"],
  ["asset_detector", "Asset Detector"],
  ["store_reading", "Store Reading Model"],
  ["campaign_strategy", "Campaign Strategy Model"],
  ["ad_copy_generation", "Ad Copy Model"],
  ["content_rewrite", "Content Rewrite Model"],
  ["video_script_generation", "Video Script Model"],
  ["image_generation", "Image Generation Model"],
  ["video_generation", "Video Generation Model"],
  ["risk_review", "Risk Review Model"],
  ["analytics_summary", "Analytics Summary Model"],
  ["ai_recommendations", "AI Recommendations Model"],
  ["brief_validation", "Brief Validation"],
  ["content_context_loader", "Content Context Loader"],
];

export const VISIBILITY = [
  ["customer_visible", "ظاهر للعميل"],
  ["internal_only", "داخلي فقط"],
  ["reviewer_only", "للمراجع فقط"],
  ["admin_only", "للمدير فقط"],
];

export const NEXT_WORKFLOWS = [
  ["", "لا يفتح مسارًا آخر"],
  ["store_intelligence", "Store Intelligence"],
  ["campaign_generation", "Campaign Generation"],
  ["content_generation", "Content Generation"],
  ["image_generation", "Image Generation"],
  ["video_generation", "Video Generation"],
  ["risk_review", "Risk Review"],
  ["publishing", "Publishing"],
  ["analytics_recommendation", "Analytics Recommendation"],
];

export const STRUCTURED_INPUT_SOURCES = [
  {
    value: "store_setup",
    label: "إعداد المتجر",
    fields: ["store_name", "store_category", "channels", "audience", "offer", "data_source"],
  },
  {
    value: "product_catalog",
    label: "كتالوج المنتجات",
    fields: ["product_name", "category", "price", "product_description", "product_media"],
  },
  {
    value: "asset_library",
    label: "مكتبة الأصول",
    fields: ["selected_assets", "linked_assets", "asset_usage", "review_notes"],
  },
  {
    value: "campaign_wizard",
    label: "معالج الحملة",
    fields: ["audience", "offer", "channels", "cta", "selected_assets"],
  },
  {
    value: "content_studio",
    label: "استوديو المحتوى",
    fields: ["campaign_content", "cta", "previous_outputs"],
  },
  {
    value: "data_sources",
    label: "مصادر البيانات",
    fields: ["data_source", "performance_metrics", "channels"],
  },
  {
    value: "review_preview",
    label: "المراجعة والمعاينة",
    fields: ["review_notes", "campaign_content", "previous_outputs"],
  },
  {
    value: "analytics",
    label: "التحليلات",
    fields: ["performance_metrics", "channels", "previous_outputs"],
  },
  {
    value: "manual",
    label: "إدخال يدوي",
    fields: ["manual_notes", "audience", "offer", "cta"],
  },
];

export const INPUT_FIELD_OPTIONS = [
  ["product_name", "اسم المنتج"],
  ["category", "التصنيف"],
  ["price", "السعر"],
  ["product_description", "وصف المنتج"],
  ["product_media", "وسائط المنتج"],
  ["linked_assets", "الأصول المرتبطة"],
  ["selected_assets", "الأصول المختارة"],
  ["channels", "القنوات"],
  ["audience", "الجمهور"],
  ["offer", "العرض"],
  ["cta", "دعوة الإجراء"],
  ["data_source", "مصدر البيانات"],
  ["performance_metrics", "مؤشرات الأداء"],
  ["review_notes", "ملاحظات المراجعة"],
  ["campaign_content", "محتوى الحملة"],
  ["previous_outputs", "المخرجات السابقة"],
  ["store_name", "اسم المتجر"],
  ["store_category", "تصنيف المتجر"],
  ["asset_usage", "استخدام الأصل"],
  ["manual_notes", "ملاحظات يدوية"],
  ["store_url", "رابط المتجر"],
  ["workspace_id", "مساحة العمل"],
  ["language_hint", "تلميح اللغة"],
  ["social_account", "الحساب الاجتماعي"],
  ["campaign_brief", "ملخص الحملة"],
  ["store_context", "سياق المتجر"],
  ["product_context", "سياق المنتج"],
  ["product_analysis_summary", "ملخص تحليل المنتج"],
  ["product_campaign_suggestions", "اقتراحات الحملات"],
  ["product_candidates", "منتجات مرشحة"],
  ["asset_context", "سياق الأصول"],
  ["approved_assets", "أصول تمت مراجعتها"],
  ["channel_specs", "مواصفات القناة"],
  ["governance_context", "سياق الحوكمة"],
  ["analytics_metrics", "مؤشرات التحليلات"],
  ["content_id", "مرجع المحتوى"],
  ["manual_input", "إدخال يدوي"],
  ["previous_step_output", "مخرج الخطوة السابقة"],
  ["brand_insights", "إشارات العلامة"],
  ["selected_channels", "القنوات المختارة"],
  ["content_context", "سياق المحتوى"],
  ["customer_video_brief", "شرح فيديو للعميل"],
  ["internal_video_prompt", "مطالبة داخلية محجوبة"],
  ["risk_clearance", "نتيجة مراجعة المخاطر"],
  ["brand_rules", "قواعد العلامة"],
];

export const OUTPUT_TYPE_OPTIONS = [
  ["content_draft", "نص حملة"],
  ["generated_asset", "أصل بصري"],
  ["customer_visible_brief", "سيناريو فيديو"],
  ["analytics_recommendation", "ملخص تحليلي"],
  ["campaign_strategy", "توصية"],
  ["brand_insights", "بيانات منظمة"],
  ["product_candidates", "قائمة مهام"],
  ["product_analysis_summary", "ملخص تحليل المنتج"],
  ["product_campaign_suggestions", "اقتراحات الحملات"],
  ["risk_report", "قرار مراجعة"],
  ["asset_candidates", "أصول مرشحة"],
  ["raw_store_snapshot", "لقطة بيانات"],
  ["audience_insights", "تحليل جمهور"],
  ["internal_prompt", "مخرج داخلي محجوب"],
  ["publishing_item", "عنصر جاهزية نشر"],
];

export const OUTPUT_FORMATS = [
  ["text", "نص"],
  ["json", "JSON"],
  ["preview_card", "بطاقة معاينة"],
  ["image", "صورة"],
  ["video", "فيديو"],
  ["table", "جدول"],
  ["list", "قائمة"],
];

export const DESTINATION_OPTIONS = [
  ["store_setup", "إعداد المتجر"],
  ["store_profile", "ملف المتجر"],
  ["data_sources", "مصادر البيانات"],
  ["product_catalog", "كتالوج المنتجات"],
  ["asset_library", "مكتبة الأصول"],
  ["campaign_detail", "تفاصيل الحملة"],
  ["content_studio", "استوديو المحتوى"],
  ["review", "المراجعة والمعاينة"],
  ["publishing_queue", "جاهزية النشر"],
  ["analytics", "التحليلات"],
  ["workflow_runs", "تشغيلات النظام"],
  ["audit_log", "سجل المراجعة"],
];

export const TRANSITION_CONDITIONS = [
  ["always", "دائمًا"],
  ["after_review", "بعد المراجعة"],
  ["no_warnings", "عند عدم وجود تحذيرات"],
  ["user_approved", "عند اعتماد المستخدم"],
  ["valid_output", "عند وجود مخرج صالح"],
];

export const TRIGGER_TYPES = [
  ["manual", "تشغيل يدوي"],
  ["campaign_created", "عند إنشاء حملة"],
  ["content_approved", "عند اعتماد محتوى"],
  ["new_data_arrived", "عند وصول بيانات جديدة"],
  ["previous_workflow_completed", "عند اكتمال مسار سابق"],
  ["publish_scheduled", "عند جدولة نشر"],
  ["performance_threshold", "عند تجاوز مؤشر أداء"],
  ["review_requested", "عند طلب مراجعة"],
];

export const START_CONDITIONS = [
  ["manual_always", "دائمًا عند التشغيل اليدوي"],
  ["required_data_complete", "عند اكتمال البيانات المطلوبة"],
  ["user_approved", "بعد اعتماد المستخدم"],
  ["valid_previous_output", "عند وجود مخرج صالح من مسار سابق"],
  ["data_source_event", "عند وصول حدث من مصدر بيانات"],
  ["performance_limit", "عند تجاوز حد أداء"],
];

export const EVENT_SOURCES = [
  ["manual", "إدخال يدوي"],
  ["store_setup", "إعداد المتجر"],
  ["campaign_wizard", "معالج الحملة"],
  ["content_studio", "استوديو المحتوى"],
  ["review_preview", "المراجعة والمعاينة"],
  ["data_sources", "مصادر البيانات"],
  ["analytics", "التحليلات"],
  ["previous_workflow", "مسار سابق"],
];

export const TRIGGER_START_WHEN_OPTIONS = [
  ["required_data_complete", "عند اكتمال البيانات المطلوبة"],
  ["always", "دائمًا عند التشغيل"],
  ["after_previous_approved", "بعد اعتماد المسار السابق"],
  ["new_event_received", "عند وصول حدث جديد"],
  ["manual_by_user", "عند تشغيل يدوي بواسطة المستخدم"],
  ["performance_threshold_exceeded", "عند تجاوز مؤشر الأداء"],
  ["campaign_status_changed", "عند تغيير حالة الحملة"],
  ["scheduled_time", "في وقت مجدول"],
];

export const TRIGGER_UPDATE_POLICIES = [
  ["", "لا توجد سياسة تحديث محددة"],
  ["replace_previous_output", "استبدال المخرج السابق"],
  ["append_to_previous", "إضافة إلى المخرج السابق"],
  ["create_new_version", "إنشاء نسخة جديدة"],
  ["merge_with_existing", "دمج مع البيانات القائمة"],
  ["skip_if_unchanged", "تخطي إذا لم تتغير البيانات"],
];

export const DESTINATION_FIELD_MAP = {
  store_setup: [
    ["store_name", "اسم المتجر"],
    ["store_category", "تصنيف المتجر"],
    ["channels", "القنوات"],
    ["audience", "الجمهور"],
    ["offer", "العرض"],
  ],
  store_profile: [
    ["store_description", "وصف المتجر"],
    ["brand_voice", "نبرة العلامة"],
    ["competitor_analysis", "تحليل المنافسين"],
  ],
  data_sources: [
    ["data_source", "مصدر البيانات"],
    ["performance_metrics", "مؤشرات الأداء"],
    ["analytics_metrics", "مؤشرات التحليلات"],
  ],
  product_catalog: [
    ["product_name", "اسم المنتج"],
    ["product_description", "وصف المنتج"],
    ["product_media", "وسائط المنتج"],
    ["category", "التصنيف"],
    ["price", "السعر"],
  ],
  asset_library: [
    ["selected_assets", "الأصول المختارة"],
    ["linked_assets", "الأصول المرتبطة"],
    ["asset_usage", "استخدام الأصل"],
  ],
  campaign_detail: [
    ["campaign_brief", "ملخص الحملة"],
    ["audience", "الجمهور المستهدف"],
    ["channels", "القنوات"],
    ["cta", "دعوة الإجراء"],
    ["offer", "العرض"],
  ],
  content_studio: [
    ["campaign_content", "محتوى الحملة"],
    ["content_draft", "مسودة المحتوى"],
    ["previous_outputs", "المخرجات السابقة"],
    ["cta", "دعوة الإجراء"],
  ],
  review: [
    ["review_notes", "ملاحظات المراجعة"],
    ["campaign_content", "محتوى الحملة"],
    ["previous_outputs", "المخرجات السابقة"],
  ],
  publishing_queue: [
    ["publishing_item", "عنصر جاهزية النشر"],
    ["scheduled_date", "تاريخ الجدولة"],
    ["channel_specs", "مواصفات القناة"],
  ],
  analytics: [
    ["performance_metrics", "مؤشرات الأداء"],
    ["analytics_metrics", "مؤشرات التحليلات"],
    ["previous_outputs", "المخرجات السابقة"],
  ],
  workflow_runs: [
    ["run_result", "نتيجة التشغيل"],
    ["run_log", "سجل التشغيل"],
  ],
  audit_log: [
    ["audit_entry", "سجل المراجعة"],
    ["risk_report", "تقرير المخاطر"],
  ],
};

export const TABS = [
  ["builder", "مصمم مسارات التشغيل"],
  ["map", "خريطة تدفق البيانات"],
  ["contracts", "ضوابط المخرجات"],
  ["runs", "مراقبة التشغيلات"],
  ["test", "اختبار المسار"],
];

export const MODEL_ROUTE_CATALOG = {
  store_reading: {
    taskLabel: "قراءة المتجر وتحليل صفحاته",
    primaryModel: "Gemini Store Reader",
    fallback: ["GPT Analysis"],
    maxCostPerRun: "0.35",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  product_extraction: {
    taskLabel: "استخراج المنتجات والتصنيفات",
    primaryModel: "Gemini Store Reader",
    fallback: ["GPT Analysis"],
    maxCostPerRun: "0.20",
    approvalAbove: "0.75",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  product_analysis: {
    taskLabel: "تحليل المنتج",
    primaryModel: "GPT Analysis",
    fallback: ["Gemini Store Reader"],
    maxCostPerRun: "0.30",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  campaign_strategy: {
    taskLabel: "تحليل وتخطيط الحملة",
    primaryModel: "GPT Analysis",
    fallback: ["Claude Risk Reviewer"],
    maxCostPerRun: "0.50",
    approvalAbove: "1.50",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  ad_copy_generation: {
    taskLabel: "توليد النصوص الإعلانية",
    primaryModel: "GPT Campaign Writer",
    fallback: ["Claude Risk Reviewer"],
    maxCostPerRun: "0.25",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  content_rewrite: {
    taskLabel: "إعادة صياغة المحتوى",
    primaryModel: "GPT Campaign Writer",
    fallback: ["Claude Risk Reviewer"],
    maxCostPerRun: "0.25",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  video_script_generation: {
    taskLabel: "كتابة سكربت الفيديو",
    primaryModel: "GPT Campaign Writer",
    fallback: ["Claude Risk Reviewer"],
    maxCostPerRun: "0.40",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  video_generation: {
    taskLabel: "توليد الفيديو",
    primaryModel: "Runway Video",
    fallback: ["Flux Image"],
    maxCostPerRun: "8.00",
    approvalAbove: "3.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  risk_review: {
    taskLabel: "مراجعة المخاطر والادعاءات",
    primaryModel: "Claude Risk Reviewer",
    fallback: ["GPT Analysis"],
    maxCostPerRun: "0.40",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  image_generation: {
    taskLabel: "توليد الصور",
    primaryModel: "Flux Image",
    fallback: ["Gemini Store Reader"],
    maxCostPerRun: "1.50",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
  ai_recommendations: {
    taskLabel: "توصيات التحسين",
    primaryModel: "GPT Analysis",
    fallback: ["Gemini Store Reader"],
    maxCostPerRun: "0.30",
    approvalAbove: "1.00",
    humanReviewRequired: true,
    blockAutoPublish: true,
    status: "linked",
  },
};

export const RUNS = [
  {
    id: "wf-001",
    workflowType: "store_intelligence",
    title: "فحص متجر النمو",
    status: "completed",
    currentStep: "user_review",
    modelUsed: "Gemini Store Reader",
    cost: 0.18,
    duration: "38s",
    owner: "System",
    source: "Store Setup",
    createdAt: "منذ 12 دقيقة",
    inputSummary: "store_url + workspace_id + language_hint",
    outputSummary: "store_profile + product_catalog + asset_library",
    warnings: ["حقوق بعض الصور تحتاج مراجعة", "تم إخفاء أي بيانات حساسة من العرض"],
    error: "",
    steps: [
      ["queued", "إدخال المهمة للطابور", "0s", "completed"],
      ["crawl_store_pages", "زحف صفحات المتجر", "6s", "completed"],
      ["extract_products", "استخراج المنتجات", "14s", "completed"],
      ["detect_assets", "رصد الأصول والصور", "9s", "completed"],
      ["user_review", "بوابة مراجعة بشرية", "9s", "waiting_for_review"],
    ],
  },
  {
    id: "wf-002",
    workflowType: "campaign_generation",
    title: "توليد حملة عطر X",
    status: "running",
    currentStep: "content_plan",
    modelUsed: "GPT Campaign Writer",
    cost: 0.32,
    duration: "1m 12s",
    owner: "أحمد",
    source: "Campaign Wizard",
    createdAt: "منذ 6 دقائق",
    inputSummary: "campaign_brief + selected_products + channels + cta",
    outputSummary: "قيد توليد content_plan وchannel_variants",
    warnings: [],
    error: "",
    steps: [
      ["queued", "إدخال المهمة للطابور", "0s", "completed"],
      ["build_prompt", "بناء Prompt داخلي", "8s", "completed"],
      ["content_plan", "بناء خطة المحتوى", "55s", "running"],
      ["risk_review", "مراجعة المخاطر", "—", "waiting_for_review"],
    ],
  },
  {
    id: "wf-003",
    workflowType: "video_generation",
    title: "فيديو Reel قصير",
    status: "waiting_for_review",
    currentStep: "risk_review",
    modelUsed: "Runway Video",
    cost: 3.7,
    duration: "2m 40s",
    owner: "محمد",
    source: "Content Studio",
    createdAt: "منذ 22 دقيقة",
    inputSummary: "video_script + product_image + duration=15s",
    outputSummary: "video_draft يحتاج مراجعة قبل الجدولة",
    warnings: ["تكلفة التشغيل مرتفعة", "النشر التلقائي غير مسموح"],
    error: "",
    steps: [
      ["queued", "إدخال المهمة للطابور", "0s", "completed"],
      ["validate_assets", "فحص الأصول", "10s", "completed"],
      ["submit_video_job", "إرسال طلب التوليد", "38s", "completed"],
      ["risk_review", "مراجعة المخاطر", "1m 52s", "waiting_for_review"],
    ],
  },
  {
    id: "wf-004",
    workflowType: "asset_analysis",
    title: "تحليل أصول حملة العيد",
    status: "failed",
    currentStep: "rights_review",
    modelUsed: "Gemini Store Reader",
    cost: 0.22,
    duration: "44s",
    owner: "System",
    source: "Asset Library",
    createdAt: "منذ 45 دقيقة",
    inputSummary: "4 images + brand_logo + product_description",
    outputSummary: "فشل بسبب أصل يحتاج مراجعة حقوق",
    warnings: ["صورة تحتوي شخصًا واضحًا وقد تحتاج موافقة"],
    error: "ASSET_RIGHTS_REVIEW_REQUIRED",
    steps: [
      ["queued", "إدخال المهمة للطابور", "0s", "completed"],
      ["detect_dimensions", "قراءة المقاسات", "9s", "completed"],
      ["quality_check", "فحص الجودة", "16s", "completed"],
      ["rights_review", "مراجعة حقوق الاستخدام", "19s", "failed"],
    ],
  },
];

export const STATUS_META = {
  running: ["قيد التشغيل", "blue"],
  waiting_for_review: ["بانتظار مراجعة", "amber"],
  completed: ["مكتمل", "green"],
  failed: ["فشل", "red"],
  cancelled: ["ملغي", "slate"],
};

export const DATA_PROCESSING_PIPELINE = [
  {
    name: "تحديد مصدر البيانات",
    status: "جاهز للتصميم",
    input: "نوع المتجر وقناة البيع الأساسية",
    output: "خطة جمع البيانات",
    layer: "إعداد المتجر",
    tool: "اختيار واجهي",
    blocked: "لا يوجد حظر في النموذج الأولي",
    warnings: "تحتاج مراجعة قبل التنفيذ الحقيقي",
  },
  {
    name: "تشغيل الموصل",
    status: "غير منفذ",
    input: "إعداد الموصل ومرجع السر",
    output: "تشغيل مجدول أو يدوي لاحقًا",
    layer: "Data Sources Hub",
    tool: "Official API / Firecrawl / Browserless / Apify",
    blocked: "Backend مطلوب",
    warnings: "لا توجد موصلات نشطة من الواجهة",
  },
  {
    name: "حفظ البيانات الخام",
    status: "غير منفذ",
    input: "نتيجة الموصل",
    output: "Raw Payload",
    layer: "طبقة التخزين لاحقًا",
    tool: "Queue + Storage",
    blocked: "لا يوجد تخزين إنتاجي",
    warnings: "يلزم تحديد سياسة الاحتفاظ",
  },
  {
    name: "تطبيع البيانات",
    status: "جاهز للتصميم",
    input: "Raw Payload",
    output: "Normalized Signals",
    layer: "Processing Pipeline",
    tool: "Rule engine + classifiers",
    blocked: "لا يوجد Backend للمعالجة",
    warnings: "الخرائط الحالية واجهية فقط",
  },
  {
    name: "بناء حزمة أدلة للتحليل",
    status: "جاهز للتصميم",
    input: "البيانات المنظمة",
    output: "Evidence Pack",
    layer: "AI preparation",
    tool: "Evidence builder",
    blocked: "لا يوجد إنشاء حقيقي للحزمة",
    warnings: "يجب فصل الحقائق عن الاستنتاجات",
  },
  {
    name: "إرسال مهمة الذكاء الاصطناعي",
    status: "غير منفذ",
    input: "Evidence Pack + مخطط الإخراج",
    output: "Structured AI result",
    layer: "AI orchestration",
    tool: "Model Route + Prompt Governance",
    blocked: "لا يوجد استدعاء نموذج حقيقي",
    warnings: "تحتاج مطالبة معتمدة وحد تكلفة",
  },
  {
    name: "مراجعة المخرجات",
    status: "مطلوبة",
    input: "Structured AI result",
    output: "ReviewFinding",
    layer: "Review Preview",
    tool: "Human review",
    blocked: "لا يعتمد أي مخرج ظاهر دون مراجعة",
    warnings: "النشر التلقائي غير مسموح",
  },
  {
    name: "إعادة استخدام النتائج",
    status: "جاهز للتصميم",
    input: "مخرجات معتمدة",
    output: "Strategy / Brief / Readiness",
    layer: "Commercial journey",
    tool: "Shared contracts",
    blocked: "لا يوجد حفظ إنتاجي",
    warnings: "إعادة الاستخدام يجب أن تحفظ المصدر والقيود",
  },
];

export const PROCESSING_READINESS_CHECKS = [
  ["نوع المتجر محدد", "مخطط من إعداد المتجر"],
  ["خطة جمع البيانات موجودة", "متوفرة كتصميم واجهي"],
  ["الموصل مهيأ", "مهيأ فقط"],
  ["مرجع السر موجود", "اسم مرجع لاحقًا فقط"],
  ["Backend مطلوب", "نعم"],
  ["مخطط المخرجات محدد", "محدد كعقد واجهي"],
  ["مراجعة بشرية مطلوبة", "نعم"],
  ["النشر التلقائي غير مسموح", "نعم"],
];

export const EVIDENCE_PACK_ITEMS = [
  "ملخص المتجر",
  "المنتجات",
  "الأصول",
  "القنوات",
  "السياسات",
  "إشارات اجتماعية عند توفر موصل مصرح",
  "حدود البيانات",
  "مستوى الثقة",
  "نوع المهمة",
  "مخطط الإخراج",
];

export const REUSABLE_OUTPUTS = [
  ["StoreStrategicPlan", "إعداد المتجر، Dashboard، معالج الحملة"],
  ["SocialStoreIntelligenceReport", "إعداد المتجر، Dashboard، معالج الحملة، استوديو المحتوى"],
  ["ProductMarketingPriority", "كتالوج المنتجات، معالج الحملة"],
  ["AssetGapReport", "مكتبة الأصول، استوديو المحتوى"],
  ["CampaignBrief", "معالج الحملة، استوديو المحتوى"],
  ["CampaignContentOutput", "استوديو المحتوى، المراجعة والمعاينة"],
  ["ReviewFinding", "المراجعة والمعاينة، جدولة النشر"],
  ["PublishingReadiness", "جدولة النشر، Dashboard"],
];
