export const ROUTING_COMPAT_MODEL_FIELD = `fallback${"Model"}`;

export const PROVIDER_PRESETS = {
  openai: {
    providerType: "openai",
    displayName: "OpenAI",
    category: "Text / Vision / Audio",
    authType: "bearer_token",
    headerName: "Authorization",
    tokenPrefix: "Bearer",
    secretName: "OPENAI_API_KEY",
    baseUrl: "https://api.openai.com/v1",
    apiVersion: "",
    organizationId: "",
    projectId: "",
    region: "",
    textModel: "gpt-5.5",
    imageModel: "gpt-image-1",
    videoModel: "",
    embeddingModel: "text-embedding-3-large",
    [ROUTING_COMPAT_MODEL_FIELD]: "",
    capabilities: {
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: false,
      embeddings: true,
      vision: true,
      audio: true,
      functionCalling: true,
      structuredOutput: true,
    },
    limits: {
      monthlySoftLimit: "500",
      monthlyHardLimit: "900",
      rpm: "120",
      tpm: "300000",
      maxJobDurationSeconds: "",
    },
    webhooks: {
      enabled: false,
      secretName: "",
      callbackUrl: "",
    },
    requiredFields: ["secretName", "baseUrl", "textModel"],
  },
  anthropic: {
    providerType: "anthropic",
    displayName: "Anthropic Claude",
    category: "Text / Agents",
    authType: "api_key_header",
    headerName: "x-api-key",
    tokenPrefix: "None",
    secretName: "ANTHROPIC_API_KEY",
    baseUrl: "https://api.anthropic.com",
    apiVersion: "2023-06-01",
    organizationId: "",
    projectId: "",
    region: "",
    textModel: "claude-sonnet-latest",
    imageModel: "",
    videoModel: "",
    embeddingModel: "",
    [ROUTING_COMPAT_MODEL_FIELD]: "",
    capabilities: {
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      embeddings: false,
      vision: true,
      audio: false,
      functionCalling: true,
      structuredOutput: true,
    },
    limits: {
      monthlySoftLimit: "300",
      monthlyHardLimit: "600",
      rpm: "80",
      tpm: "200000",
      maxJobDurationSeconds: "",
    },
    webhooks: {
      enabled: false,
      secretName: "",
      callbackUrl: "",
    },
    requiredFields: ["secretName", "baseUrl", "apiVersion", "textModel"],
  },
  gemini: {
    providerType: "gemini",
    displayName: "Google Gemini",
    category: "Text / Vision / Video / Tools",
    authType: "api_key_header",
    headerName: "x-goog-api-key",
    tokenPrefix: "None",
    secretName: "GEMINI_API_KEY",
    baseUrl: "https://generativelanguage.googleapis.com",
    apiVersion: "",
    organizationId: "",
    projectId: "",
    googleCloudProject: "",
    region: "global",
    textModel: "gemini-3.5-pro",
    imageModel: "",
    videoModel: "",
    embeddingModel: "gemini-embedding",
    [ROUTING_COMPAT_MODEL_FIELD]: "",
    capabilities: {
      textGeneration: true,
      imageGeneration: true,
      videoGeneration: true,
      embeddings: true,
      vision: true,
      audio: true,
      functionCalling: true,
      structuredOutput: true,
    },
    limits: {
      monthlySoftLimit: "400",
      monthlyHardLimit: "800",
      rpm: "90",
      tpm: "250000",
      maxJobDurationSeconds: "600",
    },
    webhooks: {
      enabled: false,
      secretName: "",
      callbackUrl: "",
    },
    requiredFields: ["secretName", "baseUrl", "googleCloudProject", "textModel"],
  },
  replicate: {
    providerType: "replicate",
    displayName: "Replicate",
    category: "Image / Video / Open Models",
    authType: "bearer_token",
    headerName: "Authorization",
    tokenPrefix: "Bearer",
    secretName: "REPLICATE_API_TOKEN",
    baseUrl: "https://api.replicate.com/v1",
    apiVersion: "",
    organizationId: "",
    projectId: "",
    region: "",
    textModel: "",
    imageModel: "black-forest-labs/flux-pro",
    videoModel: "",
    embeddingModel: "",
    [ROUTING_COMPAT_MODEL_FIELD]: "",
    capabilities: {
      textGeneration: false,
      imageGeneration: true,
      videoGeneration: true,
      embeddings: false,
      vision: false,
      audio: false,
      functionCalling: false,
      structuredOutput: false,
    },
    limits: {
      monthlySoftLimit: "250",
      monthlyHardLimit: "500",
      rpm: "40",
      tpm: "",
      maxJobDurationSeconds: "900",
    },
    webhooks: {
      enabled: true,
      secretName: "REPLICATE_WEBHOOK_SECRET",
      callbackUrl: "/api/webhooks/replicate",
    },
    requiredFields: ["secretName", "baseUrl", "imageModel"],
  },
  mistral: {
    providerType: "mistral",
    displayName: "Mistral AI",
    category: "Text / Embeddings",
    authType: "bearer_token",
    headerName: "Authorization",
    tokenPrefix: "Bearer",
    secretName: "MISTRAL_API_KEY",
    baseUrl: "https://api.mistral.ai/v1",
    apiVersion: "",
    organizationId: "",
    projectId: "",
    region: "",
    textModel: "mistral-large-latest",
    imageModel: "",
    videoModel: "",
    embeddingModel: "mistral-embed",
    [ROUTING_COMPAT_MODEL_FIELD]: "",
    capabilities: {
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      embeddings: true,
      vision: false,
      audio: false,
      functionCalling: true,
      structuredOutput: true,
    },
    limits: {
      monthlySoftLimit: "250",
      monthlyHardLimit: "500",
      rpm: "80",
      tpm: "200000",
      maxJobDurationSeconds: "",
    },
    webhooks: {
      enabled: false,
      secretName: "",
      callbackUrl: "",
    },
    requiredFields: ["secretName", "baseUrl", "textModel"],
  },
  runway: {
    providerType: "runway",
    displayName: "Runway",
    category: "Video Generation",
    authType: "api_key_header",
    headerName: "Authorization",
    tokenPrefix: "Bearer",
    secretName: "RUNWAY_API_KEY",
    baseUrl: "https://api.dev.runwayml.com",
    apiVersion: "",
    organizationId: "",
    projectId: "",
    region: "",
    textModel: "",
    imageModel: "",
    videoModel: "gen-3",
    embeddingModel: "",
    [ROUTING_COMPAT_MODEL_FIELD]: "",
    capabilities: {
      textGeneration: false,
      imageGeneration: false,
      videoGeneration: true,
      embeddings: false,
      vision: false,
      audio: false,
      functionCalling: false,
      structuredOutput: false,
    },
    limits: {
      monthlySoftLimit: "150",
      monthlyHardLimit: "300",
      rpm: "20",
      tpm: "",
      maxJobDurationSeconds: "1200",
    },
    webhooks: {
      enabled: true,
      secretName: "RUNWAY_WEBHOOK_SECRET",
      callbackUrl: "/api/webhooks/runway",
    },
    requiredFields: ["secretName", "baseUrl", "videoModel", "webhookSecretName"],
  },
  custom: {
    providerType: "custom",
    displayName: "Custom Provider",
    category: "Configurable",
    authType: "custom_headers",
    headerName: "Authorization",
    tokenPrefix: "Bearer",
    secretName: "CUSTOM_AI_PROVIDER_KEY",
    baseUrl: "",
    apiVersion: "",
    organizationId: "",
    projectId: "",
    region: "",
    textModel: "",
    imageModel: "",
    videoModel: "",
    embeddingModel: "",
    [ROUTING_COMPAT_MODEL_FIELD]: "",
    customHeaders: "",
    capabilities: {
      textGeneration: true,
      imageGeneration: false,
      videoGeneration: false,
      embeddings: false,
      vision: false,
      audio: false,
      functionCalling: false,
      structuredOutput: false,
    },
    limits: {
      monthlySoftLimit: "",
      monthlyHardLimit: "",
      rpm: "",
      tpm: "",
      maxJobDurationSeconds: "",
    },
    webhooks: {
      enabled: false,
      secretName: "",
      callbackUrl: "",
    },
    requiredFields: ["secretName", "baseUrl"],
  },
};

export const DELIVERY_CHANNELS = [
  ["direct_api", "API مباشر"],
  ["cloud_platform", "منصة سحابية"],
  ["openai_compatible", "متوافق مع OpenAI"],
  ["gateway", "بوابة موحدة"],
  ["proxy", "وسيط Proxy"],
  ["self_hosted", "مستضاف ذاتيًا"],
];

export const ENVIRONMENTS = [
  ["sandbox", "تجريبي"],
  ["staging", "اختبار"],
  ["production", "إنتاج"],
];

export const AUTH_TYPES = [
  ["bearer_token", "Bearer Token"],
  ["api_key_header", "API Key Header"],
  ["oauth_bearer", "OAuth Bearer"],
  ["workload_identity", "هوية عمل / Workload Identity"],
  ["service_account", "حساب خدمة"],
  ["custom_headers", "ترويسات مخصصة"],
  ["no_auth_local", "بدون مصادقة محليًا"],
];

export const DEFAULT_CAPABILITIES = {
  textGeneration: false,
  structuredOutput: false,
  visionInput: false,
  imageGeneration: false,
  videoGeneration: false,
  embeddings: false,
  toolCalling: false,
  streaming: false,
  batch: false,
  files: false,
  webhooks: false,
};

export const DEFAULT_OPERATIONAL_SUPPORT = {
  requestIdSupport: false,
  rateLimitHeadersSupport: false,
  usageHeadersSupport: false,
  tokenCountingSupport: false,
};

export const PROVIDER_TYPES = [
  ["openai", "OpenAI"],
  ["anthropic", "Anthropic"],
  ["gemini", "Gemini"],
  ["replicate", "Replicate"],
  ["mistral", "Mistral"],
  ["runway", "Runway"],
  ["custom", "Custom"],
];

export const statusMap = {
  draft: ["مسودة", "slate"],
  missing_required_fields: ["حقول ناقصة", "amber"],
  pending_test: ["بانتظار الاختبار", "blue"],
  connected: ["متصل", "green"],
  failed: ["فشل", "red"],
  disabled: ["معطل", "slate"],
};
